---
title: "Data Science Workshops 2026: Visualization and Public Data"
format: html
---

Welcome to the 2026 Data Science Workshops!

::: {.callout-note collapse=true}
## Schedule

::: panel-tabset

{{< include Blanding.qmd >}}

{{< include Roosevelt.qmd >}}

:::

:::

::: callout-note

## Workshop 

Prerequisites

If you are planning to participate in the workshop, you should bring:

1. A laptop    
If you don't have a computer you can bring, please contact [Eric Rowley (Blanding)](mailto://eric.rowley@usu.edu) or [Don Busenbark (Roosevelt)](mailto://don.busenbark@usu.edu) to arrange to use a loaner laptop.
2. R and RStudio software (see instructions below)

{{< include setup.qmd >}}

:::

## Resources & Links

- [Cheat Sheets for R packages](https://opensource.posit.co/resources/cheatsheets/)
    - [Convenient set of cheat sheets used for Stat 1080 (introductory statistics) at USU](https://srvanderplas.github.io/stat1080/demos/r-cheat-sheets.pdf)


- **Tidy Tuesday** is an R organization that posts a new public data set every week, and has since 2018. You can find the [data](https://github.com/rfordatascience/tidytuesday#datasets), but there are also people who [livestream analyzing the data](https://www.youtube.com/results?search_query=%23tidytuesday), and those videos are on YouTube and are an excellent way to learn how to use the `tidyverse` set of packages (which include `ggplot2`)

    